repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
{%- if cookiecutter.code_qa == 'ruff' %}
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.278
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
{%- endif %}
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
{%- if cookiecutter.code_qa == 'flake8' %}
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
{%- elif cookiecutter.code_qa == 'pylint' %}
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
{%- endif %}
{%- if cookiecutter.circle_ci_config != 'none' %}
  - repo: https://github.com/AleksaC/circleci-cli-py
    rev: v0.1.27660
    hooks:
      - id: circle-ci-validator
{% endif %}
