version: 2.1

orbs:
  python: circleci/python@2.1.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: eu.gcr.io/hummingbird-technologies/services/{{cookiecutter.project_slug}}
    docker:
      - image: cimg/python:3.10
    resource_class: small

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - setup_remote_docker:
          version: "20.10.18"
          docker_layer_caching: true
      - run: docker build --progress=plain -t $IMAGE_NAME:latest .
      - run: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - image.tar
    environment:
      IMAGE_NAME: eu.gcr.io/hummingbird-technologies/services/{{cookiecutter.project_slug}}
      DOCKER_BUILDKIT: 1
      GIT_COMMIT: $CIRCLE_SHA1

  test:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: "20.10.18"
          docker_layer_caching: true
      - run: docker load -i /tmp/workspace/image.tar
      - run: docker run --name {{cookiecutter.app_name}} --entrypoint "pip3" $IMAGE_NAME install -r requirements/development.txt
      - run: docker commit {{cookiecutter.app_name}} {{cookiecutter.app_name}}
      - run: docker run --entrypoint "black" --line-length=100 --check .
      - {% if cookiecutter.code_qa == 'pylint' %}run: docker run --entrypoint "pylint" {{cookiecutter.app_name}}/ tests/ --rcfile=.pylintrc{% elif cookiecutter.code_qa == 'flake8' %}run: docker run --entrypoint "flake8" {{cookiecutter.app_name}}/ tests/{%- endif %}
      - run: docker run --entrypoint "mypy" {{cookiecutter.app_name}}/
      - run: docker run --entrypoint "pytest" tests --verbose
      - store_test_results:
          path: results
      - store_artifacts:
          path: $HOME/test-results/coverage.html
          destination: coverage-metrics

  push-docker-image:
    executor: docker-publisher
    environment:
      PIPELINE_NUMBER: << pipeline.number >>
    parameters:
      env:
        type: string
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          command: docker load -i /tmp/workspace/image.tar
          name: Load image from workspace
      - run:
          command: |
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
            docker tag $IMAGE_NAME:$CIRCLE_SHA1 $IMAGE_NAME:<< parameters.env >>-$PIPELINE_NUMBER
            docker tag $IMAGE_NAME:$CIRCLE_SHA1 $IMAGE_NAME:<< parameters.env >>
          name: Tag image
      - run:
          command: echo $GSA_KEY | docker login -u _json_key --password-stdin https://eu.gcr.io
          name: Log in to Google Container Registry
      - run:
          command: docker push --all-tags $IMAGE_NAME
          name: Push image

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build

      # Staging
      - push-docker-image:
          name: push-docker-image-staging
          env: staging
          requires:
            - test
          context:
            - gcp-secrets
          filters:
            branches:
              only: {% if cookiecutter.circle_ci_config == "trunk" %}develop{% elif cookiecutter.circle_ci_config == "CI-CD" %}main{% endif %}

      # Production
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: main
      - push-docker-image:
          name: push-docker-image-prod
          env: prod
          requires:
            - hold
          context:
            - gcp-secrets
          filters:
            branches:
              only: main
